### ISSUE TITLE
Blacklisting fails with TypeError (Chrome)

### ISSUE THREAD

**Issue by gguillotte** [oladon/PaizoCampaignTools#1]
When clicking the blacklist icon next to a user, nothing appears to happen. In the JS console, I see an error in `pctBlacklist`:

``` javascript
var pctBlacklist = {
    blackListener: function(evt, cb) {
        var target = evt.currentTarget,
            username = target.getAttribute("username"),
            action = target.getAttribute("action");

        chrome.extension.sendRequest({storage: ['blacklist']}, function(response) {
            var blacklist = blacklistToArray(response.storage.blacklist);
            ...
```

`response` is undefined, and it fails with an exception: "TypeError: Cannot read property 'storage' of undefined."

Seen on 
- Chromium 45.0.2453.0 (64-bit), OS X
- Chrome 44.0.2403.89 (64-bit), OS X
- Chrome 44.0.2403.107 (64-bit), OS X

**Comment by oladon** [comment]
Thanks for the report. I'll look into it and get a fix out as soon as I can!
